---
deployment:
  tasks:
    - export DEPLOYPATH=/home/digitalabcs/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp apps.html $DEPLOYPATH
    - /bin/cp account-deletion.html $DEPLOYPATH
    - /bin/cp ai_transparency.html $DEPLOYPATH
    - /bin/cp children-privacy.html $DEPLOYPATH
    - /bin/cp children-terms.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp eea-uk-privacy-notice.html $DEPLOYPATH
    - /bin/cp eula.html $DEPLOYPATH
    - /bin/cp insights.html $DEPLOYPATH
    - /bin/cp legal.html $DEPLOYPATH
    - /bin/cp privacy.html $DEPLOYPATH
    - /bin/cp support.html $DEPLOYPATH
    - /bin/cp terms.html $DEPLOYPATH
    - /bin/cp us-privacy-notice.html $DEPLOYPATH
    - /bin/cp llms.txt $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp insights.php $DEPLOYPATH
    - /bin/cp article.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp htaccess $DEPLOYPATH/.htaccess
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp -r assets/* $DEPLOYPATH/assets/
    - /bin/mkdir -p $DEPLOYPATH/apps
    - /bin/cp -r apps/* $DEPLOYPATH/apps/
